name: Daily Build and Release

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch: 

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'  # Adjust this to your Go version

      - name: Install dependencies
        run: go mod download

      - name: Run Go app
        run: go run main.go --sources=debt   # Adjust this to your app's entry point

      - name: Compress output
        run: gzip out.db

      - name: Create Release and Upload Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name="release-${{ github.run_number }}"
          release_name="Daily Release ${{ github.run_number }}"
          
          gh release create "$tag_name" \
            --title "$release_name" \
            --notes "Automated daily release" \
            out.db.gz
