name: Daily Build and Release

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Install dependencies
        run: go mod download

      - name: Run Go app
        run: go run main.go

      - name: Compress output
        run: gzip out.db

      - name: Create Release and Upload Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name="release-${{ github.run_number }}"
          release_name="Estonian Companies Data $(date +'%Y-%m-%d %H-%M')"

          gh release create "$tag_name" \
            --title "$release_name" \
            --notes "Latest data about Estonian companies" \
            out.db.gz
